version: '3.8'

services:
  web:
    build: ./web
    ports:
      - '8082:80'
  api:
    build: ./api
    env_file: .env
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
    - ./database.sql:/docker-entrypoint-initdb.d/database.sql
  
networks:
  default:
    name: docker-stack